services:
  app:
    container_name: music_app
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    env_file: ".env"
    restart: always
    depends_on:
      - db
      - redis
  
  db:
    container_name: music_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - music_volume:/var/lib/postgresql/data
    image: docker.arvancloud.ir/postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PROD_POSTGRES_PASSWORD}
      - POSTGRES_USER=${PROD_POSTGRES_USER}
      - POSTGRES_DB=${PROD_POSTGRES_DB}
      - shared_preload_libraries=pg_stat_statements
      - pg_stat_statements.track=all

  redis:
    volumes:
      - redis_data:/data
    container_name: music_db_redis
    image: docker.arvancloud.ir/redis:8.2-alpine
    restart: always
    expose:
      - 6379

  nginx:
    container_name: music_nginx
    volumes:
      - static_files:/var/www/static/
      - flower:/var/www/static/flower/
      - log_nginx:/var/log/nginx
      # - log_rotate:/var/log/rotate/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile

  dj-admin-pannel:
    build:
      context: /root/online-melo
      dockerfile: Dockerfile
    env_file: "/root/online-melo/.env"
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - static_files:/home/app/staticfiles
      - flower:/home/app/static_files_flowers
    depends_on:
      - db
      - app
      - redis
      - nginx

  dj-celery:
    build:
      context: /root/online-melo
      dockerfile: Dockerfile
    env_file: "/root/online-melo/.env"
    restart: always
    depends_on:
      - dj-admin-pannel
    entrypoint: "celery -A melo_music.dj_celery worker -l INFO"

  flower:
    build:
      context: /root/online-melo
      dockerfile: Dockerfile
    env_file: "/root/online-melo/.env"
    restart: always
    expose:
      - 5555
    depends_on:
      - dj-celery
    entrypoint: "celery -A melo_music.dj_celery flower --port=5555"

  pghero:
    depends_on:
      - db
    container_name: pghero_gapchi
    ports:
      - "8080:8080"
    expose:
      - 8080
    image: ankane/pghero
    environment:
      # - DATABASE_URL=postgres://[username]:[password]@[hostname]:[port]/[database_name]
      - DATABASE_URL=${PG_HERO_DATABASE_URL}
      - PGHERO_USERNAME=${PGHERO_USERNAME}
      - PGHERO_PASSWORD=${PGHERO_PASSWORD}
  
  pgadmin:
    depends_on:
      - db
    container_name: pgadmin_music
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  music_volume:
  static_files:
  redis_data:
  flower:
  log_nginx:
  pgadmin_data:
  # log_rotate:
