services:
  app:
    container_name: music_app
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    env_file: ".env"
    restart: always
    depends_on:
      - db
      - redis
  
  db:
    container_name: music_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - music_volume:/var/lib/postgresql/data
    image: docker.arvancloud.ir/postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PROD_POSTGRES_PASSWORD}
      - POSTGRES_USER=${PROD_POSTGRES_USER}
      - POSTGRES_DB=${PROD_POSTGRES_DB}

  redis:
    container_name: music_db_redis
    image: docker.arvancloud.ir/redis:8.2-alpine
    restart: always
    expose:
      - 6379

  nginx:
    container_name: music_nginx
    volumes:
      - static_files:/var/www/static/
    ports:
      - "80:80"
      - "443:443"
    restart: always
    # depends_on:
    #   - dj-admin-pannel
    # command: ["nginx", "-g", "daemon off;"]
    build:
      context: nginx
      dockerfile: Dockerfile
  
  # ui-nginx:
  #   image: docker.arvancloud.ir/uozi/nginx-ui:latest
  #   container_name: music-nginx-ui
  #   ports:
  #     - "8080:8080"
  #     - "8443:8443"
  #   volumes:
  #     - nginx-ui-data:/etc/nginx-ui
  #     - nginx:/etc/nginx
  #     - certs:/ets/ssl/private

  # dj-admin-pannel:
  #   build:
  #     context: dj-admin-pannel
  #     dockerfile: Dockerfile
  #   env_file: ".env"
  #   restart: always
  #   expose:
  #     - 8000
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - static_files:/home/app/dj-admin/staticfiles
  #   depends_on:
  #     - db
  #     - app

volumes:
  music_volume:
  static_files:
  # nginx-ui-data:
  # nginx:
  # certs:
