/var/log/nginx/*.log {
    daily
    rotate 30
    missingok
    compress
    delaycompress
    notifempty
    sharedscripts
    create 0640 nginx adm

    prerotate
        TODAY_DIR="/var/log/nginx/$(date +%Y)/$(date +%m)/$(date +%d)"
        mkdir -p "$TODAY_DIR"
        # chown nginx:nginx "$TODAY_DIR"
    endscript

    postrotate
        # if [ -f /var/run/nginx.pid ]; then
        #     kill -USR1 $(cat /var/run/nginx.pid)
        # fi
        TODAY_DIR="/var/log/nginx/$(date +%Y)/$(date +%m)/$(date +%d)"
        for file in /var/log/nginx/*.log; do
            [ -f "$file" ] && mv "$file" "$TODAY_DIR/$(basename "$file")"
        done
    endscript
}
