/var/log/nginx/*.log {
    daily
    missingok
    rotate 30
    dateext
    dateformat -%Y/%m/%d
    create 0640 nginx adm
    compress
    delaycompress
    notifempty
    sharedscripts
    prerotate
        mkdir -p /var/log/nginx/$(date +%Y)/$(date +%m)/$(date +%d)
    endscript
    postrotate
        # Tell nginx to reopen logs
        if [ -f /var/run/nginx.pid ]; then
            kill -USR1 $(cat /var/run/nginx.pid)
        fi
    endscript
    olddir /var/log/nginx/$(date +%Y)/$(date +%m)/$(date +%d)
}
