user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    client_max_body_size 16M;
    client_body_buffer_size 256k;
    proxy_read_timeout 30;
    proxy_request_buffering on;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    sendfile on;

    # Redirect HTTP to HTTPS for all domains
    server {
        listen 80;
        server_name api.meloricdns.com pannel.meloricdns.com;
        return 301 https://$host$request_uri;
    }

    # node api
    server {
        listen 443 ssl;
        server_name api.meloricdns.com;
        http2 on;

        ssl_certificate /certbot/api.meloricdns.com/fullchain1.pem;
        ssl_certificate_key /certbot/api.meloricdns.com/privkey1.pem;

        location / {
            proxy_pass http://music_app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    # Admin panel subdomain - Django Admin
    server {
        listen 443 ssl;
        server_name pannel.meloricdns.com;
        http2 on;

        ssl_certificate /certbot/api.meloricdns.com/fullchain1.pem;
        ssl_certificate_key /certbot/api.meloricdns.com/privkey1.pem;

    #     location /static/ {
    #         alias /var/www/static/;
    #         gzip on;
    #     }
    # }

        location / {
            proxy_pass http://dj-admin-pannel:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    server {
        listen 443 ssl;
        server_name pghere.meloricdns.com;
        http2 on;

        ssl_certificate /certbot/api.meloricdns.com/fullchain1.pem;
        ssl_certificate_key /certbot/api.meloricdns.com/privkey1.pem;

        location / {
            proxy_pass http://music_pghere:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    };
}