user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    client_max_body_size 16M; # max request body
    client_body_buffer_size 256k; # buffer size
    proxy_read_timeout 30; # time out for read data
    proxy_request_buffering on; # enable buffer
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    sendfile on;

    # redirect
    server {
        listen 80;
        server_name meloricdns.com;
        return 301 https://$host$request_uri;
    }

    # ssl
    server {
        listen 443 ssl;
        server_name meloricdns.com;
        http2 on;

        # ssk certificate
        ssl_certificate /certbot/api.meloricdns.com/fullchain1.pem;
        ssl_certificate_key /certbot/api.meloricdns.com/privkey1.pem;

        # ssl config security
        # include /certbot/api.meloricdns.com/options-ssl-nginx.conf;
        # ssl_dhparam /certbot/api.meloricdns.com/ssl-dhparams.pem;

        location / {
            proxy_pass http://music_app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /static/ {
            alias /var/www/static/;
            gzip on;
        }

        # config django-admin
        # location /admin/ {
        #     proxy_pass http://dj-admin-pannel:8000/admin/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto https;

        #     # increase request body
        #     client_max_body_size 20M;
        # }
    }
}